export * from "./String-Interpolation/string-interpolation.component";
export * from "./event-binding/event-binding.component";
export * from "./products/products.component";
export * from "./products/product-thumbnail/product-thumbnail.component";
export * from "./property-binding/property-binding.component";
export * from "./twoway-binding/twoway-binding.component";
export { DashboardComponent } from './dashboard/dashboard.component';
export { HeaderComponent } from './header/header.component';
export { FooterComponent } from './footer/footer.component';
export * from "./products/product-details/product-details.component";
export * from "./students/students.component";
export * from "./students/student-details/student-details.component";
export * from "./students/student-edit/student-edit.component";
export * from "./sign-up/sign-up.component";
export { TempProductsComponent } from './temp-products/temp-products.component';